### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-config-profile#9]
User Review:

Allow a person with a fresh mind to read the guide and execute the steps described in the guide, test whether each step is clear enough to understand, and no logic errors.

Review and walkthrough by a non-SME or a new user with a critical and fresh pair of eyes:

- [x] Record the time it takes to go through the entire guide
- [x] Test each step in the guide is clear and easy to understand
- [x] Ensure all hotspots work
- [x] Ensure all URLs work and open new tab
- [x] Ensure no logic errors
- [x] Report anything that does not work
- [x] Report anything usability issues (confusing or hard to follow)
- [x] Does the guide achieve basic understanding/working knowledge of the topic in the guide?

**Comment by mbuamuh** [comment]
- [x] [https://guides-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/guides/microprofile-config-profile.html#switching-to-development-environment](url)
- Replace `META-INF/microprofile-config.properties` with `query/src/main/resources/META-INF/microprofile-config.properties`, in order to be more specific and make it clearer to the reader
- Hotspot `system/server.xml` does not work.
